version: '3'
services:
  db:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: szymon
      MONGO_INITDB_ROOT_PASSWORD: dxFxazbvuV5GkuHW
    networks:
      - backend_network
#    ports:
##      - "27017:27017"
#      - "20:27017"
  backend:
    build: .
    image: smartdormapp/backend:latest
    volumes:
      - /home/debian/certs:/app/key
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: gunicorn -b 0.0.0.0:3000 --keyfile /app/key/privkey.pem --certfile /app/key/fullchain.pem backend:app
    environment:
      DATABASE_LINK: 'mongodb://szymon:dxFxazbvuV5GkuHW@db:27017'
      API_KEY: "XLl1g1s8JOv0Qd8zuD9TqB8tXHOLEELv8FCAHSSg354lM3PKquocKCrzYHSXH8tUJz0Qj8wgG6URyZfIkD8vk7OhedQAyp5u9p1OMPaezsiWw8SHY1ioKYGBnwCVcMKW"
    networks:
      - backend_network
#  backup:
#    build: ./backup
#    volumes:
#      - ./backup:/backup
#    command: mongodump --out /backup --host db --username szymon --password dxFxazbvuV5GkuHW
#    depends_on:
#      - db
#    networks:
#      - backend_network
#    restart: always
#    environment:
#      CRON_SCHEDULE: "0 0 * * *"
#    entrypoint: sh -c 'echo "0 0 * * * /usr/bin/mongodump --out /backup --host db --username szymon --password dxFxazbvuV5GkuHW > /proc/1/fd/1 2>/proc/1/fd/2" | crontab - && cron -f -L /dev/stdout'
networks:
  backend_network: