name: Docker Build and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - name: Build and push Docker image with commit tag
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: smartdormapp/backend:${{ steps.slug.outputs.sha8 }}

      - name: Build and push Docker image with latest tag
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: smartdormapp/backend:latest
